export type ClinicalTrialSite = {
  id: string;
  siteName: string;
  piName: string;
  region: string;
  therapeuticArea: string;
  startupDays: number;
  eligiblePatientCount: number;
  historicalEnrollmentRate: number;
  retentionRate: number;
  previousTrialCount: number;
};

export const clinicalTrialSites: ClinicalTrialSite[] = [
  {
    id: "site-201",
    siteName: "North Harbor Research Center",
    piName: "Dr. Alicia Moreno",
    region: "Northeast",
    therapeuticArea: "Oncology",
    startupDays: 62,
    eligiblePatientCount: 340,
    historicalEnrollmentRate: 11.4,
    retentionRate: 89,
    previousTrialCount: 31,
  },
  {
    id: "site-202",
    siteName: "Crescent Valley Medical Institute",
    piName: "Dr. Marcus Bennett",
    region: "Southeast",
    therapeuticArea: "Cardiology",
    startupDays: 74,
    eligiblePatientCount: 410,
    historicalEnrollmentRate: 10.1,
    retentionRate: 86,
    previousTrialCount: 27,
  },
  {
    id: "site-203",
    siteName: "Lakeview Neurology Associates",
    piName: "Dr. Priya Nandakumar",
    region: "Midwest",
    therapeuticArea: "Neurology",
    startupDays: 68,
    eligiblePatientCount: 290,
    historicalEnrollmentRate: 8.2,
    retentionRate: 91,
    previousTrialCount: 22,
  },
  {
    id: "site-204",
    siteName: "Sunridge Clinical Partners",
    piName: "Dr. Helena Foster",
    region: "West",
    therapeuticArea: "Endocrinology",
    startupDays: 57,
    eligiblePatientCount: 360,
    historicalEnrollmentRate: 9.3,
    retentionRate: 88,
    previousTrialCount: 19,
  },
  {
    id: "site-205",
    siteName: "Riverpoint Immunology Group",
    piName: "Dr. Samir Qureshi",
    region: "Southwest",
    therapeuticArea: "Immunology",
    startupDays: 81,
    eligiblePatientCount: 255,
    historicalEnrollmentRate: 7.1,
    retentionRate: 84,
    previousTrialCount: 16,
  },
  {
    id: "site-206",
    siteName: "Pine State Academic Trials Unit",
    piName: "Dr. Katherine Lang",
    region: "Northeast",
    therapeuticArea: "Pulmonology",
    startupDays: 95,
    eligiblePatientCount: 230,
    historicalEnrollmentRate: 6.4,
    retentionRate: 82,
    previousTrialCount: 14,
  },
  {
    id: "site-207",
    siteName: "Golden Prairie Research Network",
    piName: "Dr. Elliot Huang",
    region: "Midwest",
    therapeuticArea: "Gastroenterology",
    startupDays: 72,
    eligiblePatientCount: 305,
    historicalEnrollmentRate: 8.9,
    retentionRate: 87,
    previousTrialCount: 24,
  },
  {
    id: "site-208",
    siteName: "Blue Mesa Trial Center",
    piName: "Dr. Renee Alvarez",
    region: "Southwest",
    therapeuticArea: "Oncology",
    startupDays: 88,
    eligiblePatientCount: 275,
    historicalEnrollmentRate: 7.7,
    retentionRate: 81,
    previousTrialCount: 18,
  },
  {
    id: "site-209",
    siteName: "Coastal Heart and Vascular Research",
    piName: "Dr. Daniel Osei",
    region: "West",
    therapeuticArea: "Cardiology",
    startupDays: 66,
    eligiblePatientCount: 450,
    historicalEnrollmentRate: 12.2,
    retentionRate: 90,
    previousTrialCount: 34,
  },
  {
    id: "site-210",
    siteName: "Cedar Grove Clinical Sciences",
    piName: "Dr. Mei Chen",
    region: "Southeast",
    therapeuticArea: "Rheumatology",
    startupDays: 79,
    eligiblePatientCount: 245,
    historicalEnrollmentRate: 6.8,
    retentionRate: 85,
    previousTrialCount: 15,
  },
  {
    id: "site-211",
    siteName: "Frontier Neurocognitive Institute",
    piName: "Dr. Jacob Whitaker",
    region: "Midwest",
    therapeuticArea: "Neurology",
    startupDays: 102,
    eligiblePatientCount: 210,
    historicalEnrollmentRate: 5.9,
    retentionRate: 78,
    previousTrialCount: 12,
  },
  {
    id: "site-212",
    siteName: "Eastgate Metabolic Research",
    piName: "Dr. Isabella Romero",
    region: "Northeast",
    therapeuticArea: "Endocrinology",
    startupDays: 63,
    eligiblePatientCount: 380,
    historicalEnrollmentRate: 10.8,
    retentionRate: 92,
    previousTrialCount: 29,
  },
  {
    id: "site-213",
    siteName: "South Bay Precision Trials",
    piName: "Dr. Thomas Kingsley",
    region: "West",
    therapeuticArea: "Dermatology",
    startupDays: 54,
    eligiblePatientCount: 265,
    historicalEnrollmentRate: 8.5,
    retentionRate: 93,
    previousTrialCount: 21,
  },
  {
    id: "site-214",
    siteName: "Magnolia Women’s Health Research",
    piName: "Dr. Lila Thompson",
    region: "Southeast",
    therapeuticArea: "Women’s Health",
    startupDays: 70,
    eligiblePatientCount: 325,
    historicalEnrollmentRate: 9.7,
    retentionRate: 88,
    previousTrialCount: 26,
  },
  {
    id: "site-215",
    siteName: "Redwood Rare Disease Collaborative",
    piName: "Dr. Noah Harrington",
    region: "West",
    therapeuticArea: "Rare Disease",
    startupDays: 128,
    eligiblePatientCount: 120,
    historicalEnrollmentRate: 3.6,
    retentionRate: 95,
    previousTrialCount: 11,
  },
  {
    id: "site-216",
    siteName: "Metroline Internal Medicine Trials",
    piName: "Dr. Farah Siddiqui",
    region: "Northeast",
    therapeuticArea: "Infectious Disease",
    startupDays: 84,
    eligiblePatientCount: 390,
    historicalEnrollmentRate: 9.1,
    retentionRate: 83,
    previousTrialCount: 20,
  },
  {
    id: "site-217",
    siteName: "Prairie Ridge Oncology Network",
    piName: "Dr. Benjamin Cole",
    region: "Midwest",
    therapeuticArea: "Oncology",
    startupDays: 91,
    eligiblePatientCount: 315,
    historicalEnrollmentRate: 7.9,
    retentionRate: 80,
    previousTrialCount: 17,
  },
  {
    id: "site-218",
    siteName: "Desert Springs Pulmonary Research",
    piName: "Dr. Carla Jimenez",
    region: "Southwest",
    therapeuticArea: "Pulmonology",
    startupDays: 76,
    eligiblePatientCount: 285,
    historicalEnrollmentRate: 8.1,
    retentionRate: 86,
    previousTrialCount: 18,
  },
  {
    id: "site-219",
    siteName: "Harborlight Gastro Clinical Unit",
    piName: "Dr. Omar Rahman",
    region: "Northeast",
    therapeuticArea: "Gastroenterology",
    startupDays: 67,
    eligiblePatientCount: 300,
    historicalEnrollmentRate: 8.7,
    retentionRate: 89,
    previousTrialCount: 23,
  },
  {
    id: "site-220",
    siteName: "Summit Peak Multi-Specialty Trials",
    piName: "Dr. Evelyn Park",
    region: "Mountain",
    therapeuticArea: "Immunology",
    startupDays: 109,
    eligiblePatientCount: 205,
    historicalEnrollmentRate: 5.1,
    retentionRate: 76,
    previousTrialCount: 9,
  },
];

export const clinicalTrialSiteById: Record<string, ClinicalTrialSite> = Object.fromEntries(
  clinicalTrialSites.map((site) => [site.id, site]),
);

export const clinicalTrialSiteRegions = Array.from(
  new Set(clinicalTrialSites.map((site) => site.region)),
).sort();

export const clinicalTrialSiteTherapeuticAreas = Array.from(
  new Set(clinicalTrialSites.map((site) => site.therapeuticArea)),
).sort();

export function getClinicalTrialSiteById(siteId: string) {
  return clinicalTrialSiteById[siteId];
}
